### ISSUE TITLE
`axios: 0.21.4` Cross-Site Request Forgery Vulnerability

### ISSUE THREAD

**Issue by kamadorueda** [Rutter/rutter-link-base#10]
this library uses axios 0.21: https://github.com/Rutter/rutter-link-base/blob/77db8bdc2b4701261a985aace498c6ffbc1a1129/package.json#L49

which has a vulnerability:
https://github.com/advisories/GHSA-wf5p-g6vw-rhxx

> An issue discovered in Axios 0.8.1 through 1.5.1 inadvertently reveals the confidential XSRF-TOKEN stored in cookies by including it in the HTTP header X-XSRF-TOKEN for every request made to any host allowing attackers to view sensitive information.

please consider updating to the latest version

**Comment by jayp** [comment]
Thanks for reporting @kamadorueda  - as it happens we didn't even use that axios in this repo.
